spring:
  application:
    name: seller-api
  datasource:
    url: jdbc:mysql://localhost:3306/auction_platform?characterEncoding=utf8&useSSL=false
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
  mail:
    username: 1838566218@qq.com
    password: nlyxamscvrbaeacf
    host: smtp.qq.com
    port: 587
    protocol: smtp
    default-encoding: UTF-8
    properties:
      mail:
        smtp:
          # 表示SMTP发送邮件，需要进行身份验证
          auth: true
          starttls:
            enable: true
            required: true
  data:
    redis:
      host: localhost
      port: 6379
# mybatis-plus配置
mybatis-plus:
  global-config:
    db-config:
      table-prefix: tb_
